# Import libraries

In [1]:
import pandas as pd
from datetime import datetime, timedelta

# Getting the data

In [2]:
today = datetime.strftime(datetime.today(),'%Y-%m-%d')

today

'2020-09-29'

In [3]:
url = 'https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-'
covid_countries = pd.read_excel(url+today+'.xlsx')

covid_countries.head(16)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,2020-09-29,29,9,2020,12,3,Afghanistan,AF,AFG,38041757.0,Asia,1.114565
1,2020-09-28,28,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.343261
2,2020-09-27,27,9,2020,35,0,Afghanistan,AF,AFG,38041757.0,Asia,1.540413
3,2020-09-26,26,9,2020,6,2,Afghanistan,AF,AFG,38041757.0,Asia,1.540413
4,2020-09-25,25,9,2020,16,0,Afghanistan,AF,AFG,38041757.0,Asia,1.614016
5,2020-09-24,24,9,2020,25,5,Afghanistan,AF,AFG,38041757.0,Asia,1.645560
6,2020-09-23,23,9,2020,71,2,Afghanistan,AF,AFG,38041757.0,Asia,1.642931
7,2020-09-22,22,9,2020,30,3,Afghanistan,AF,AFG,38041757.0,Asia,1.524640
8,2020-09-21,21,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.698134
9,2020-09-20,20,9,2020,125,4,Afghanistan,AF,AFG,38041757.0,Asia,1.892657
10,2020-09-19,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
11,2020-09-18,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
12,2020-09-17,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
13,2020-09-16,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
14,2020-09-15,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159
15,2020-09-14,14,9,2020,75,0,Afghanistan,AF,AFG,38041757.0,Asia,1.456294

# Preparing the dataset

## Renaming columns

In [4]:
covid_countries = covid_countries.rename(columns={'countriesAndTerritories': 'countries',
                                                  'countryterritoryCode': 'countryCode',
                                                  'continentExp': 'continent'})
covid_countries.head()

,dateRep,day,month,year,cases,deaths,countries,geoId,countryCode,popData2019,continent,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,2020-07-24,24,7,2020,13,0,Afghanistan,AF,AFG,38041757.0,Asia,5.309955
1,2020-07-23,23,7,2020,188,21,Afghanistan,AF,AFG,38041757.0,Asia,5.946098
2,2020-07-22,22,7,2020,112,4,Afghanistan,AF,AFG,38041757.0,Asia,5.606997
3,2020-07-21,21,7,2020,140,5,Afghanistan,AF,AFG,38041757.0,Asia,5.864608
4,2020-07-20,20,7,2020,174,17,Afghanistan,AF,AFG,38041757.0,Asia,6.634814

In [5]:
covid_countries.dtypes

dateRep                                                       datetime64[ns]
day                                                                    int64
month                                                                  int64
year                                                                   int64
cases                                                                  int64
deaths                                                                 int64
countries                                                             object
geoId                                                                 object
countryCode                                                           object
popData2019                                                          float64
continent                                                             object
Cumulative_number_for_14_days_of_COVID-19_cases_per_100000           float64
dtype: object

## Getting important columns

In [6]:
covid_countries = covid_countries[['dateRep', 'day', 'month', 'year',
                                   'geoId', 'countries', 'countryCode', 'continent',
                                   'cases', 'deaths']]

In [7]:
covid_countries.head()

,dateRep,day,month,year,geoId,countries,countryCode,continent,cases,deaths
0,2020-07-24,24,7,2020,AF,Afghanistan,AFG,Asia,13,0
1,2020-07-23,23,7,2020,AF,Afghanistan,AFG,Asia,188,21
2,2020-07-22,22,7,2020,AF,Afghanistan,AFG,Asia,112,4
3,2020-07-21,21,7,2020,AF,Afghanistan,AFG,Asia,140,5
4,2020-07-20,20,7,2020,AF,Afghanistan,AFG,Asia,174,17

## Creating a datatime

In [8]:
covid_countries['datetime'] = pd.to_datetime(covid_countries[['year', 'month', 'day']])

covid_countries.head()

,dateRep,day,month,year,geoId,countries,countryCode,continent,cases,deaths,datetime
0,2020-07-24,24,7,2020,AF,Afghanistan,AFG,Asia,13,0,2020-07-24
1,2020-07-23,23,7,2020,AF,Afghanistan,AFG,Asia,188,21,2020-07-23
2,2020-07-22,22,7,2020,AF,Afghanistan,AFG,Asia,112,4,2020-07-22
3,2020-07-21,21,7,2020,AF,Afghanistan,AFG,Asia,140,5,2020-07-21
4,2020-07-20,20,7,2020,AF,Afghanistan,AFG,Asia,174,17,2020-07-20

## Selecting and Reordering columns

In [9]:
covid_countries = covid_countries[['dateRep', 'datetime', 'day', 'month', 'year',
                                   'geoId', 'countries', 'countryCode', 'continent',
                                   'cases', 'deaths']]

covid_countries.head()

,dateRep,datetime,day,month,year,geoId,countries,countryCode,continent,cases,deaths
0,2020-07-24,2020-07-24,24,7,2020,AF,Afghanistan,AFG,Asia,13,0
1,2020-07-23,2020-07-23,23,7,2020,AF,Afghanistan,AFG,Asia,188,21
2,2020-07-22,2020-07-22,22,7,2020,AF,Afghanistan,AFG,Asia,112,4
3,2020-07-21,2020-07-21,21,7,2020,AF,Afghanistan,AFG,Asia,140,5
4,2020-07-20,2020-07-20,20,7,2020,AF,Afghanistan,AFG,Asia,174,17

In [10]:
covid_countries = covid_countries[['dateRep', 'datetime',
                                   'geoId', 'countries', 'countryCode', 'continent',
                                   'cases', 'deaths']]

covid_countries.head()

,dateRep,datetime,geoId,countries,countryCode,continent,cases,deaths
0,2020-07-24,2020-07-24,AF,Afghanistan,AFG,Asia,13,0
1,2020-07-23,2020-07-23,AF,Afghanistan,AFG,Asia,188,21
2,2020-07-22,2020-07-22,AF,Afghanistan,AFG,Asia,112,4
3,2020-07-21,2020-07-21,AF,Afghanistan,AFG,Asia,140,5
4,2020-07-20,2020-07-20,AF,Afghanistan,AFG,Asia,174,17

## Creating a cases_at

In [11]:
covid_countries['cases_at'] = covid_countries['datetime'] - timedelta(days=1)
covid_countries.head()

,dateRep,datetime,geoId,countries,countryCode,continent,cases,deaths,cases_at
0,2020-07-24,2020-07-24,AF,Afghanistan,AFG,Asia,13,0,2020-07-23
1,2020-07-23,2020-07-23,AF,Afghanistan,AFG,Asia,188,21,2020-07-22
2,2020-07-22,2020-07-22,AF,Afghanistan,AFG,Asia,112,4,2020-07-21
3,2020-07-21,2020-07-21,AF,Afghanistan,AFG,Asia,140,5,2020-07-20
4,2020-07-20,2020-07-20,AF,Afghanistan,AFG,Asia,174,17,2020-07-19

In [12]:
covid_countries = covid_countries[['dateRep', 'datetime', 'cases_at',
                                   'geoId', 'countries', 'countryCode', 'continent',
                                   'cases', 'deaths']]

In [13]:
covid_countries[covid_countries.countries == 'Afghanistan'][['cases']].head()

   cases
0     13
1    188
2    112
3    140
4    174

## Removing comman from countries

In [14]:
countries_no_comman_and_underscore = []

for country in covid_countries['countries']:
    country = country.replace(',', '')
    country = country.replace('_', ' ')
    countries_no_comman_and_underscore.append(country)
    
countries_no_comman_and_underscore = pd.DataFrame(countries_no_comman_and_underscore, columns=['countries'])
countries_no_comman_and_underscore.head()

     countries
0  Afghanistan
1  Afghanistan
2  Afghanistan
3  Afghanistan
4  Afghanistan

In [15]:
covid_countries = covid_countries.merge(countries_no_comman_and_underscore, left_index=True, right_index=True)
covid_countries.head()

,dateRep,datetime,cases_at,geoId,countries_x,countryCode,continent,cases,deaths,countries_y
0,2020-07-24,2020-07-24,2020-07-23,AF,Afghanistan,AFG,Asia,13,0,Afghanistan
1,2020-07-23,2020-07-23,2020-07-22,AF,Afghanistan,AFG,Asia,188,21,Afghanistan
2,2020-07-22,2020-07-22,2020-07-21,AF,Afghanistan,AFG,Asia,112,4,Afghanistan
3,2020-07-21,2020-07-21,2020-07-20,AF,Afghanistan,AFG,Asia,140,5,Afghanistan
4,2020-07-20,2020-07-20,2020-07-19,AF,Afghanistan,AFG,Asia,174,17,Afghanistan

In [16]:
covid_countries[covid_countries.countries_x != covid_countries.countries_y]

,dateRep,datetime,cases_at,geoId,countries_x,countryCode,continent,cases,deaths,countries_y
915,2020-07-24,2020-07-24,2020-07-23,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
916,2020-07-23,2020-07-23,2020-07-22,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
917,2020-07-22,2020-07-22,2020-07-21,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
918,2020-07-21,2020-07-21,2020-07-20,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
919,2020-07-20,2020-07-20,2020-07-19,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
920,2020-07-19,2020-07-19,2020-07-18,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
921,2020-07-18,2020-07-18,2020-07-17,AG,Antigua_and_Barbuda,ATG,America,2,0,Antigua and Barbuda
922,2020-07-17,2020-07-17,2020-07-16,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
923,2020-07-16,2020-07-16,2020-07-15,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
924,2020-07-15,2020-07-15,2020-07-14,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
925,2020-07-14,2020-07-14,2020-07-13,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
926,2020-07-13,2020-07-13,2020-07-12,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
927,2020-07-12,2020-07-12,2020-07-11,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
928,2020-07-11,2020-07-11,2020-07-10,AG,Antigua_and_Barbuda,ATG,America,1,0,Antigua and Barbuda
929,2020-07-10,2020-07-10,2020-07-09,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
930,2020-07-09,2020-07-09,2020-07-08,AG,Antigua_and_Barbuda,ATG,America,3,0,Antigua and Barbuda
931,2020-07-08,2020-07-08,2020-07-07,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
932,2020-07-07,2020-07-07,2020-07-06,AG,Antigua_and_Barbuda,ATG,America,2,0,Antigua and Barbuda
933,2020-07-06,2020-07-06,2020-07-05,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
934,2020-07-05,2020-07-05,2020-07-04,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
935,2020-07-04,2020-07-04,2020-07-03,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
936,2020-07-03,2020-07-03,2020-07-02,AG,Antigua_and_Barbuda,ATG,America,2,0,Antigua and Barbuda
937,2020-07-02,2020-07-02,2020-07-01,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
938,2020-07-01,2020-07-01,2020-06-30,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
939,2020-06-30,2020-06-30,2020-06-29,AG,Antigua_and_Barbuda,ATG,America,1,0,Antigua and Barbuda
940,2020-06-29,2020-06-29,2020-06-28,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
941,2020-06-28,2020-06-28,2020-06-27,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
942,2020-06-27,2020-06-27,2020-06-26,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
943,2020-06-26,2020-06-26,2020-06-25,AG,Antigua_and_Barbuda,ATG,America,0,0,Antigua and Barbuda
944,2020-06-25,2020-06-25,2020-06-24,AG,Antigua_and_Barbuda,ATG,America,39,0,Antigua and Barbuda
...,...,...,...,...,...,...,...,...,...,...
31415,2020-05-25,2020-05-25,2020-05-24,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31416,2020-05-24,2020-05-24,2020-05-23,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31417,2020-05-23,2020-05-23,2020-05-22,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31418,2020-05-22,2020-05-22,2020-05-21,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31419,2020-05-21,2020-05-21,2020-05-20,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31420,2020-05-20,2020-05-20,2020-05-19,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31421,2020-05-19,2020-05-19,2020-05-18,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31422,2020-05-18,2020-05-18,2020-05-17,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31423,2020-05-17,2020-05-17,2020-05-16,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31424,2020-05-16,2020-05-16,2020-05-15,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31425,2020-05-15,2020-05-15,2020-05-14,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31426,2020-05-14,2020-05-14,2020-05-13,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31427,2020-05-13,2020-05-13,2020-05-12,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31428,2020-05-12,2020-05-12,2020-05-11,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31429,2020-05-11,2020-05-11,2020-05-10,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31430,2020-05-10,2020-05-10,2020-05-09,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31431,2020-05-09,2020-05-09,2020-05-08,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31432,2020-05-08,2020-05-08,2020-05-07,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31433,2020-05-07,2020-05-07,2020-05-06,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31434,2020-05-06,2020-05-06,2020-05-05,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31435,2020-05-05,2020-05-05,2020-05-04,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31436,2020-05-04,2020-05-04,2020-05-03,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31437,2020-05-03,2020-05-03,2020-05-02,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31438,2020-05-02,2020-05-02,2020-05-01,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31439,2020-05-01,2020-05-01,2020-04-30,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31440,2020-04-30,2020-04-30,2020-04-29,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31441,2020-04-29,2020-04-29,2020-04-28,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31442,2020-04-28,2020-04-28,2020-04-27,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31443,2020-04-27,2020-04-27,2020-04-26,EH,Western_Sahara,ESH,Africa,0,0,Western Sahara
31444,2020-04-26,2020-04-26,2020-04-25,EH,Western_Sahara,ESH,Africa,6,0,Western Sahara

In [17]:
covid_countries = covid_countries.rename(columns={'countries_y': 'countries'})
covid_countries.head()

,dateRep,datetime,cases_at,geoId,countries_x,countryCode,continent,cases,deaths,countries
0,2020-07-24,2020-07-24,2020-07-23,AF,Afghanistan,AFG,Asia,13,0,Afghanistan
1,2020-07-23,2020-07-23,2020-07-22,AF,Afghanistan,AFG,Asia,188,21,Afghanistan
2,2020-07-22,2020-07-22,2020-07-21,AF,Afghanistan,AFG,Asia,112,4,Afghanistan
3,2020-07-21,2020-07-21,2020-07-20,AF,Afghanistan,AFG,Asia,140,5,Afghanistan
4,2020-07-20,2020-07-20,2020-07-19,AF,Afghanistan,AFG,Asia,174,17,Afghanistan

In [18]:
covid_countries = covid_countries.drop(['countries_x'], axis=1)

In [19]:
covid_countries.head()

,dateRep,datetime,cases_at,geoId,countryCode,continent,cases,deaths,countries
0,2020-07-24,2020-07-24,2020-07-23,AF,AFG,Asia,13,0,Afghanistan
1,2020-07-23,2020-07-23,2020-07-22,AF,AFG,Asia,188,21,Afghanistan
2,2020-07-22,2020-07-22,2020-07-21,AF,AFG,Asia,112,4,Afghanistan
3,2020-07-21,2020-07-21,2020-07-20,AF,AFG,Asia,140,5,Afghanistan
4,2020-07-20,2020-07-20,2020-07-19,AF,AFG,Asia,174,17,Afghanistan

In [20]:
covid_countries = covid_countries[['dateRep', 'datetime', 'cases_at',
                                   'geoId', 'countries', 'countryCode', 'continent',
                                   'cases', 'deaths']]

covid_countries.head()

,dateRep,datetime,cases_at,geoId,countries,countryCode,continent,cases,deaths
0,2020-07-24,2020-07-24,2020-07-23,AF,Afghanistan,AFG,Asia,13,0
1,2020-07-23,2020-07-23,2020-07-22,AF,Afghanistan,AFG,Asia,188,21
2,2020-07-22,2020-07-22,2020-07-21,AF,Afghanistan,AFG,Asia,112,4
3,2020-07-21,2020-07-21,2020-07-20,AF,Afghanistan,AFG,Asia,140,5
4,2020-07-20,2020-07-20,2020-07-19,AF,Afghanistan,AFG,Asia,174,17

## Correcting country name

In [21]:
covid_countries = covid_countries.replace('Bonaire Saint Eustatius and Saba', 
                                          'Bonaire Sint Eustatius and Saba')

covid_countries[covid_countries.countries == 'Bonaire Saint Eustatius and Saba']

Empty DataFrame
Columns: [dateRep, datetime, cases_at, geoId, countries, countryCode, continent, cases, deaths]
Index: []

In [22]:
covid_countries = covid_countries.replace('Falkland Islands (Malvinas)',
                                          'Falkland Islands')

covid_countries[covid_countries.countries == 'Falkland Islands (Malvinas)']

Empty DataFrame
Columns: [dateRep, datetime, cases_at, geoId, countries, countryCode, continent, cases, deaths]
Index: []

## Filling null values

In [23]:
countries_code = pd.read_csv('~/covid-19/source/countries_and_codes.csv', delimiter=',')

countries_code = countries_code.rename(columns={'ISO-3166\nalpha3': 'countryCode',
                                                'fips': 'geoId',
                                                'Country': 'country'})

countries_code.head()

  countryCode geoId               country
0         AND    AN               Andorra
1         ARE    AE  United Arab Emirates
2         AFG    AF           Afghanistan
3         ATG    AC   Antigua and Barbuda
4         AIA    AV              Anguilla

In [24]:
countries_id_code_null = (covid_countries
                              [covid_countries[['geoId', 'countryCode']].isnull().any(1)]
                              .countries.unique())

countries_id_code_null = pd.DataFrame(countries_id_code_null, columns=['country'])

countries_id_code_null

                                      country
0  Cases on an international conveyance Japan
1                                     Namibia

In [25]:
codes_ids_to_update = countries_code.merge(countries_id_code_null)

codes_ids_to_update

  countryCode geoId  country
0         NAM    WA  Namibia

In [26]:
#codes_ids_to_update = (codes_ids_to_update.append(
#                            countries_code[countries_code.country.str.contains('Falkland Islands')])
#                       .reset_index(drop=True))

#codes_ids_to_update

In [27]:
codes_ids_to_update = codes_ids_to_update.set_index('country')

In [28]:
covid_countries_set_index_country = covid_countries.set_index('countries')
covid_countries_set_index_country.update(codes_ids_to_update)

In [29]:
len(covid_countries_set_index_country) == len(covid_countries)

True

In [30]:
covid_countries = covid_countries_set_index_country.reset_index()

covid_countries[covid_countries.countries == 'Western Sahara']

,countries,dateRep,datetime,cases_at,geoId,countryCode,continent,cases,deaths
31355,Western Sahara,2020-07-24,2020-07-24,2020-07-23,EH,ESH,Africa,0,0
31356,Western Sahara,2020-07-23,2020-07-23,2020-07-22,EH,ESH,Africa,0,0
31357,Western Sahara,2020-07-22,2020-07-22,2020-07-21,EH,ESH,Africa,0,0
31358,Western Sahara,2020-07-21,2020-07-21,2020-07-20,EH,ESH,Africa,0,0
31359,Western Sahara,2020-07-20,2020-07-20,2020-07-19,EH,ESH,Africa,0,0
31360,Western Sahara,2020-07-19,2020-07-19,2020-07-18,EH,ESH,Africa,0,0
31361,Western Sahara,2020-07-18,2020-07-18,2020-07-17,EH,ESH,Africa,0,0
31362,Western Sahara,2020-07-17,2020-07-17,2020-07-16,EH,ESH,Africa,0,0
31363,Western Sahara,2020-07-16,2020-07-16,2020-07-15,EH,ESH,Africa,0,0
31364,Western Sahara,2020-07-15,2020-07-15,2020-07-14,EH,ESH,Africa,5,0
31365,Western Sahara,2020-07-14,2020-07-14,2020-07-13,EH,ESH,Africa,242,0
31366,Western Sahara,2020-07-13,2020-07-13,2020-07-12,EH,ESH,Africa,0,0
31367,Western Sahara,2020-07-12,2020-07-12,2020-07-11,EH,ESH,Africa,0,0
31368,Western Sahara,2020-07-11,2020-07-11,2020-07-10,EH,ESH,Africa,0,0
31369,Western Sahara,2020-07-10,2020-07-10,2020-07-09,EH,ESH,Africa,0,0
31370,Western Sahara,2020-07-09,2020-07-09,2020-07-08,EH,ESH,Africa,0,0
31371,Western Sahara,2020-07-08,2020-07-08,2020-07-07,EH,ESH,Africa,0,0
31372,Western Sahara,2020-07-07,2020-07-07,2020-07-06,EH,ESH,Africa,0,0
31373,Western Sahara,2020-07-06,2020-07-06,2020-07-05,EH,ESH,Africa,0,0
31374,Western Sahara,2020-07-05,2020-07-05,2020-07-04,EH,ESH,Africa,0,0
31375,Western Sahara,2020-07-04,2020-07-04,2020-07-03,EH,ESH,Africa,58,0
31376,Western Sahara,2020-07-03,2020-07-03,2020-07-02,EH,ESH,Africa,0,0
31377,Western Sahara,2020-07-02,2020-07-02,2020-07-01,EH,ESH,Africa,81,0
31378,Western Sahara,2020-07-01,2020-07-01,2020-06-30,EH,ESH,Africa,172,0
31379,Western Sahara,2020-06-30,2020-06-30,2020-06-29,EH,ESH,Africa,0,0
31380,Western Sahara,2020-06-29,2020-06-29,2020-06-28,EH,ESH,Africa,0,0
31381,Western Sahara,2020-06-28,2020-06-28,2020-06-27,EH,ESH,Africa,183,0
31382,Western Sahara,2020-06-27,2020-06-27,2020-06-26,EH,ESH,Africa,0,0
31383,Western Sahara,2020-06-26,2020-06-26,2020-06-25,EH,ESH,Africa,0,0
31384,Western Sahara,2020-06-25,2020-06-25,2020-06-24,EH,ESH,Africa,0,0
...,...,...,...,...,...,...,...,...,...
31415,Western Sahara,2020-05-25,2020-05-25,2020-05-24,EH,ESH,Africa,0,0
31416,Western Sahara,2020-05-24,2020-05-24,2020-05-23,EH,ESH,Africa,0,0
31417,Western Sahara,2020-05-23,2020-05-23,2020-05-22,EH,ESH,Africa,0,0
31418,Western Sahara,2020-05-22,2020-05-22,2020-05-21,EH,ESH,Africa,0,0
31419,Western Sahara,2020-05-21,2020-05-21,2020-05-20,EH,ESH,Africa,0,0
31420,Western Sahara,2020-05-20,2020-05-20,2020-05-19,EH,ESH,Africa,0,0
31421,Western Sahara,2020-05-19,2020-05-19,2020-05-18,EH,ESH,Africa,0,0
31422,Western Sahara,2020-05-18,2020-05-18,2020-05-17,EH,ESH,Africa,0,0
31423,Western Sahara,2020-05-17,2020-05-17,2020-05-16,EH,ESH,Africa,0,0
31424,Western Sahara,2020-05-16,2020-05-16,2020-05-15,EH,ESH,Africa,0,0
31425,Western Sahara,2020-05-15,2020-05-15,2020-05-14,EH,ESH,Africa,0,0
31426,Western Sahara,2020-05-14,2020-05-14,2020-05-13,EH,ESH,Africa,0,0
31427,Western Sahara,2020-05-13,2020-05-13,2020-05-12,EH,ESH,Africa,0,0
31428,Western Sahara,2020-05-12,2020-05-12,2020-05-11,EH,ESH,Africa,0,0
31429,Western Sahara,2020-05-11,2020-05-11,2020-05-10,EH,ESH,Africa,0,0
31430,Western Sahara,2020-05-10,2020-05-10,2020-05-09,EH,ESH,Africa,0,0
31431,Western Sahara,2020-05-09,2020-05-09,2020-05-08,EH,ESH,Africa,0,0
31432,Western Sahara,2020-05-08,2020-05-08,2020-05-07,EH,ESH,Africa,0,0
31433,Western Sahara,2020-05-07,2020-05-07,2020-05-06,EH,ESH,Africa,0,0
31434,Western Sahara,2020-05-06,2020-05-06,2020-05-05,EH,ESH,Africa,0,0
31435,Western Sahara,2020-05-05,2020-05-05,2020-05-04,EH,ESH,Africa,0,0
31436,Western Sahara,2020-05-04,2020-05-04,2020-05-03,EH,ESH,Africa,0,0
31437,Western Sahara,2020-05-03,2020-05-03,2020-05-02,EH,ESH,Africa,0,0
31438,Western Sahara,2020-05-02,2020-05-02,2020-05-01,EH,ESH,Africa,0,0
31439,Western Sahara,2020-05-01,2020-05-01,2020-04-30,EH,ESH,Africa,0,0
31440,Western Sahara,2020-04-30,2020-04-30,2020-04-29,EH,ESH,Africa,0,0
31441,Western Sahara,2020-04-29,2020-04-29,2020-04-28,EH,ESH,Africa,0,0
31442,Western Sahara,2020-04-28,2020-04-28,2020-04-27,EH,ESH,Africa,0,0
31443,Western Sahara,2020-04-27,2020-04-27,2020-04-26,EH,ESH,Africa,0,0
31444,Western Sahara,2020-04-26,2020-04-26,2020-04-25,EH,ESH,Africa,6,0

In [31]:
covid_countries[covid_countries.isnull().any(1)]['countries'].unique()

array(['Cases on an international conveyance Japan'], dtype=object)

## Reordering registrations on datetime (ASC)

In [32]:
covid_countries_reorder = (covid_countries.groupby('countries')
                               .apply(lambda x: x.sort_values('datetime', ascending=True))
                               .reset_index(drop=True))

covid_countries_reorder.head()

,countries,dateRep,datetime,cases_at,geoId,countryCode,continent,cases,deaths
0,Afghanistan,2019-12-31,2019-12-31,2019-12-30,AF,AFG,Asia,0,0
1,Afghanistan,2020-01-01,2020-01-01,2019-12-31,AF,AFG,Asia,0,0
2,Afghanistan,2020-01-02,2020-01-02,2020-01-01,AF,AFG,Asia,0,0
3,Afghanistan,2020-01-03,2020-01-03,2020-01-02,AF,AFG,Asia,0,0
4,Afghanistan,2020-01-04,2020-01-04,2020-01-03,AF,AFG,Asia,0,0

In [33]:
covid_countries_reorder[covid_countries_reorder.countries == 'Afghanistan'].tail()

,countries,dateRep,datetime,cases_at,geoId,countryCode,continent,cases,deaths
192,Afghanistan,2020-07-20,2020-07-20,2020-07-19,AF,AFG,Asia,174,17
193,Afghanistan,2020-07-21,2020-07-21,2020-07-20,AF,AFG,Asia,140,5
194,Afghanistan,2020-07-22,2020-07-22,2020-07-21,AF,AFG,Asia,112,4
195,Afghanistan,2020-07-23,2020-07-23,2020-07-22,AF,AFG,Asia,188,21
196,Afghanistan,2020-07-24,2020-07-24,2020-07-23,AF,AFG,Asia,13,0

## Creating cumsum columns

In [34]:
covid_countries_reorder[['cases_cumsum', 'deaths_cumsum']] = (covid_countries_reorder
                                                                  .groupby('countries')
                                                                  .cumsum())

In [35]:
covid_countries_reorder.head()

,countries,dateRep,datetime,cases_at,geoId,countryCode,continent,cases,deaths,cases_cumsum,deaths_cumsum
0,Afghanistan,2019-12-31,2019-12-31,2019-12-30,AF,AFG,Asia,0,0,0,0
1,Afghanistan,2020-01-01,2020-01-01,2019-12-31,AF,AFG,Asia,0,0,0,0
2,Afghanistan,2020-01-02,2020-01-02,2020-01-01,AF,AFG,Asia,0,0,0,0
3,Afghanistan,2020-01-03,2020-01-03,2020-01-02,AF,AFG,Asia,0,0,0,0
4,Afghanistan,2020-01-04,2020-01-04,2020-01-03,AF,AFG,Asia,0,0,0,0

In [36]:
covid_countries_reorder[covid_countries_reorder.countries == 'Brazil']

,countries,dateRep,datetime,cases_at,geoId,countryCode,continent,cases,deaths,cases_cumsum,deaths_cumsum
4130,Brazil,2019-12-31,2019-12-31,2019-12-30,BR,BRA,America,0,0,0,0
4131,Brazil,2020-01-01,2020-01-01,2019-12-31,BR,BRA,America,0,0,0,0
4132,Brazil,2020-01-02,2020-01-02,2020-01-01,BR,BRA,America,0,0,0,0
4133,Brazil,2020-01-03,2020-01-03,2020-01-02,BR,BRA,America,0,0,0,0
4134,Brazil,2020-01-04,2020-01-04,2020-01-03,BR,BRA,America,0,0,0,0
4135,Brazil,2020-01-05,2020-01-05,2020-01-04,BR,BRA,America,0,0,0,0
4136,Brazil,2020-01-06,2020-01-06,2020-01-05,BR,BRA,America,0,0,0,0
4137,Brazil,2020-01-07,2020-01-07,2020-01-06,BR,BRA,America,0,0,0,0
4138,Brazil,2020-01-08,2020-01-08,2020-01-07,BR,BRA,America,0,0,0,0
4139,Brazil,2020-01-09,2020-01-09,2020-01-08,BR,BRA,America,0,0,0,0
4140,Brazil,2020-01-10,2020-01-10,2020-01-09,BR,BRA,America,0,0,0,0
4141,Brazil,2020-01-11,2020-01-11,2020-01-10,BR,BRA,America,0,0,0,0
4142,Brazil,2020-01-12,2020-01-12,2020-01-11,BR,BRA,America,0,0,0,0
4143,Brazil,2020-01-13,2020-01-13,2020-01-12,BR,BRA,America,0,0,0,0
4144,Brazil,2020-01-14,2020-01-14,2020-01-13,BR,BRA,America,0,0,0,0
4145,Brazil,2020-01-15,2020-01-15,2020-01-14,BR,BRA,America,0,0,0,0
4146,Brazil,2020-01-16,2020-01-16,2020-01-15,BR,BRA,America,0,0,0,0
4147,Brazil,2020-01-17,2020-01-17,2020-01-16,BR,BRA,America,0,0,0,0
4148,Brazil,2020-01-18,2020-01-18,2020-01-17,BR,BRA,America,0,0,0,0
4149,Brazil,2020-01-19,2020-01-19,2020-01-18,BR,BRA,America,0,0,0,0
4150,Brazil,2020-01-20,2020-01-20,2020-01-19,BR,BRA,America,0,0,0,0
4151,Brazil,2020-01-21,2020-01-21,2020-01-20,BR,BRA,America,0,0,0,0
4152,Brazil,2020-01-22,2020-01-22,2020-01-21,BR,BRA,America,0,0,0,0
4153,Brazil,2020-01-23,2020-01-23,2020-01-22,BR,BRA,America,0,0,0,0
4154,Brazil,2020-01-24,2020-01-24,2020-01-23,BR,BRA,America,0,0,0,0
4155,Brazil,2020-01-25,2020-01-25,2020-01-24,BR,BRA,America,0,0,0,0
4156,Brazil,2020-01-26,2020-01-26,2020-01-25,BR,BRA,America,0,0,0,0
4157,Brazil,2020-01-27,2020-01-27,2020-01-26,BR,BRA,America,0,0,0,0
4158,Brazil,2020-01-28,2020-01-28,2020-01-27,BR,BRA,America,0,0,0,0
4159,Brazil,2020-01-29,2020-01-29,2020-01-28,BR,BRA,America,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4307,Brazil,2020-06-25,2020-06-25,2020-06-24,BR,BRA,America,42725,1185,1188631,53830
4308,Brazil,2020-06-26,2020-06-26,2020-06-25,BR,BRA,America,39483,1141,1228114,54971
4309,Brazil,2020-06-27,2020-06-27,2020-06-26,BR,BRA,America,46860,990,1274974,55961
4310,Brazil,2020-06-28,2020-06-28,2020-06-27,BR,BRA,America,38693,1109,1313667,57070
4311,Brazil,2020-06-29,2020-06-29,2020-06-28,BR,BRA,America,30476,552,1344143,57622
4312,Brazil,2020-06-30,2020-06-30,2020-06-29,BR,BRA,America,24052,692,1368195,58314
4313,Brazil,2020-07-01,2020-07-01,2020-06-30,BR,BRA,America,33846,1280,1402041,59594
4314,Brazil,2020-07-02,2020-07-02,2020-07-01,BR,BRA,America,46712,1038,1448753,60632
4315,Brazil,2020-07-03,2020-07-03,2020-07-02,BR,BRA,America,48105,1252,1496858,61884
4316,Brazil,2020-07-04,2020-07-04,2020-07-03,BR,BRA,America,42223,1290,1539081,63174
4317,Brazil,2020-07-05,2020-07-05,2020-07-04,BR,BRA,America,37923,1091,1577004,64265
4318,Brazil,2020-07-06,2020-07-06,2020-07-05,BR,BRA,America,26051,602,1603055,64867
4319,Brazil,2020-07-07,2020-07-07,2020-07-06,BR,BRA,America,20229,620,1623284,65487
4320,Brazil,2020-07-08,2020-07-08,2020-07-07,BR,BRA,America,45305,1254,1668589,66741
4321,Brazil,2020-07-09,2020-07-09,2020-07-08,BR,BRA,America,44571,1223,1713160,67964
4322,Brazil,2020-07-10,2020-07-10,2020-07-09,BR,BRA,America,42619,1220,1755779,69184
4323,Brazil,2020-07-11,2020-07-11,2020-07-10,BR,BRA,America,45048,1214,1800827,70398
4324,Brazil,2020-07-12,2020-07-12,2020-07-11,BR,BRA,America,39023,1071,1839850,71469
4325,Brazil,2020-07-13,2020-07-13,2020-07-12,BR,BRA,America,24831,631,1864681,72100
4326,Brazil,2020-07-14,2020-07-14,2020-07-13,BR,BRA,America,20286,733,1884967,72833
4327,Brazil,2020-07-15,2020-07-15,2020-07-14,BR,BRA,America,41857,1300,1926824,74133
4328,Brazil,2020-07-16,2020-07-16,2020-07-15,BR,BRA,America,39924,1233,1966748,75366
4329,Brazil,2020-07-17,2020-07-17,2020-07-16,BR,BRA,America,45403,1322,2012151,76688
4330,Brazil,2020-07-18,2020-07-18,2020-07-17,BR,BRA,America,34177,1163,2046328,77851
4331,Brazil,2020-07-19,2020-07-19,2020-07-18,BR,BRA,America,28532,921,2074860,78772
4332,Brazil,2020-07-20,2020-07-20,2020-07-19,BR,BRA,America,23529,716,2098389,79488
4333,Brazil,2020-07-21,2020-07-21,2020-07-20,BR,BRA,America,20257,632,2118646,80120
4334,Brazil,2020-07-22,2020-07-22,2020-07-21,BR,BRA,America,41008,1367,2159654,81487
4335,Brazil,2020-07-23,2020-07-23,2020-07-22,BR,BRA,America,67860,1284,2227514,82771
4336,Brazil,2020-07-24,2020-07-24,2020-07-23,BR,BRA,America,59961,1311,2287475,84082

## Adding case_ordinalDay column

In [37]:
## Removing registers without cases
covid_countries_reorder = (covid_countries_reorder
                               .drop(covid_countries_reorder
                                     [(covid_countries_reorder.cases_cumsum == 0)].index))

In [38]:
covid_countries_reorder['case_ordinalDay'] = (covid_countries_reorder
                                                  .groupby('countries')['cases_at']
                                                  .diff()
                                                  .dt.days.fillna(0).astype(int))

covid_countries_reorder[['case_ordinalDay']] = (covid_countries_reorder
                                                  .groupby('countries')['case_ordinalDay']
                                                  .cumsum()+1)


covid_countries_reorder[(covid_countries_reorder.countries == 'Brazil') 
                        & (covid_countries_reorder.cases_at >= '2020-02-25')]
#covid_countries_reorder.head()
#covid_countries_reorder.info()

,countries,dateRep,datetime,cases_at,geoId,countryCode,continent,cases,deaths,cases_cumsum,deaths_cumsum,case_ordinalDay
4187,Brazil,2020-02-26,2020-02-26,2020-02-25,BR,BRA,America,1,0,1,0,1
4188,Brazil,2020-02-27,2020-02-27,2020-02-26,BR,BRA,America,0,0,1,0,2
4189,Brazil,2020-02-28,2020-02-28,2020-02-27,BR,BRA,America,0,0,1,0,3
4190,Brazil,2020-02-29,2020-02-29,2020-02-28,BR,BRA,America,0,0,1,0,4
4191,Brazil,2020-03-01,2020-03-01,2020-02-29,BR,BRA,America,1,0,2,0,5
4192,Brazil,2020-03-02,2020-03-02,2020-03-01,BR,BRA,America,0,0,2,0,6
4193,Brazil,2020-03-03,2020-03-03,2020-03-02,BR,BRA,America,0,0,2,0,7
4194,Brazil,2020-03-04,2020-03-04,2020-03-03,BR,BRA,America,0,0,2,0,8
4195,Brazil,2020-03-05,2020-03-05,2020-03-04,BR,BRA,America,1,0,3,0,9
4196,Brazil,2020-03-06,2020-03-06,2020-03-05,BR,BRA,America,5,0,8,0,10
4197,Brazil,2020-03-07,2020-03-07,2020-03-06,BR,BRA,America,5,0,13,0,11
4198,Brazil,2020-03-08,2020-03-08,2020-03-07,BR,BRA,America,0,0,13,0,12
4199,Brazil,2020-03-09,2020-03-09,2020-03-08,BR,BRA,America,12,0,25,0,13
4200,Brazil,2020-03-10,2020-03-10,2020-03-09,BR,BRA,America,0,0,25,0,14
4201,Brazil,2020-03-11,2020-03-11,2020-03-10,BR,BRA,America,9,0,34,0,15
4202,Brazil,2020-03-12,2020-03-12,2020-03-11,BR,BRA,America,18,0,52,0,16
4203,Brazil,2020-03-13,2020-03-13,2020-03-12,BR,BRA,America,25,0,77,0,17
4204,Brazil,2020-03-14,2020-03-14,2020-03-13,BR,BRA,America,21,0,98,0,18
4205,Brazil,2020-03-15,2020-03-15,2020-03-14,BR,BRA,America,23,0,121,0,19
4206,Brazil,2020-03-16,2020-03-16,2020-03-15,BR,BRA,America,79,0,200,0,20
4207,Brazil,2020-03-17,2020-03-17,2020-03-16,BR,BRA,America,34,0,234,0,21
4208,Brazil,2020-03-18,2020-03-18,2020-03-17,BR,BRA,America,57,1,291,1,22
4209,Brazil,2020-03-19,2020-03-19,2020-03-18,BR,BRA,America,137,3,428,4,23
4210,Brazil,2020-03-20,2020-03-20,2020-03-19,BR,BRA,America,193,2,621,6,24
4211,Brazil,2020-03-21,2020-03-21,2020-03-20,BR,BRA,America,283,5,904,11,25
4212,Brazil,2020-03-22,2020-03-22,2020-03-21,BR,BRA,America,224,7,1128,18,26
4213,Brazil,2020-03-23,2020-03-23,2020-03-22,BR,BRA,America,418,7,1546,25,27
4214,Brazil,2020-03-24,2020-03-24,2020-03-23,BR,BRA,America,345,9,1891,34,28
4215,Brazil,2020-03-25,2020-03-25,2020-03-24,BR,BRA,America,310,12,2201,46,29
4216,Brazil,2020-03-26,2020-03-26,2020-03-25,BR,BRA,America,232,11,2433,57,30
...,...,...,...,...,...,...,...,...,...,...,...,...
4307,Brazil,2020-06-25,2020-06-25,2020-06-24,BR,BRA,America,42725,1185,1188631,53830,121
4308,Brazil,2020-06-26,2020-06-26,2020-06-25,BR,BRA,America,39483,1141,1228114,54971,122
4309,Brazil,2020-06-27,2020-06-27,2020-06-26,BR,BRA,America,46860,990,1274974,55961,123
4310,Brazil,2020-06-28,2020-06-28,2020-06-27,BR,BRA,America,38693,1109,1313667,57070,124
4311,Brazil,2020-06-29,2020-06-29,2020-06-28,BR,BRA,America,30476,552,1344143,57622,125
4312,Brazil,2020-06-30,2020-06-30,2020-06-29,BR,BRA,America,24052,692,1368195,58314,126
4313,Brazil,2020-07-01,2020-07-01,2020-06-30,BR,BRA,America,33846,1280,1402041,59594,127
4314,Brazil,2020-07-02,2020-07-02,2020-07-01,BR,BRA,America,46712,1038,1448753,60632,128
4315,Brazil,2020-07-03,2020-07-03,2020-07-02,BR,BRA,America,48105,1252,1496858,61884,129
4316,Brazil,2020-07-04,2020-07-04,2020-07-03,BR,BRA,America,42223,1290,1539081,63174,130
4317,Brazil,2020-07-05,2020-07-05,2020-07-04,BR,BRA,America,37923,1091,1577004,64265,131
4318,Brazil,2020-07-06,2020-07-06,2020-07-05,BR,BRA,America,26051,602,1603055,64867,132
4319,Brazil,2020-07-07,2020-07-07,2020-07-06,BR,BRA,America,20229,620,1623284,65487,133
4320,Brazil,2020-07-08,2020-07-08,2020-07-07,BR,BRA,America,45305,1254,1668589,66741,134
4321,Brazil,2020-07-09,2020-07-09,2020-07-08,BR,BRA,America,44571,1223,1713160,67964,135
4322,Brazil,2020-07-10,2020-07-10,2020-07-09,BR,BRA,America,42619,1220,1755779,69184,136
4323,Brazil,2020-07-11,2020-07-11,2020-07-10,BR,BRA,America,45048,1214,1800827,70398,137
4324,Brazil,2020-07-12,2020-07-12,2020-07-11,BR,BRA,America,39023,1071,1839850,71469,138
4325,Brazil,2020-07-13,2020-07-13,2020-07-12,BR,BRA,America,24831,631,1864681,72100,139
4326,Brazil,2020-07-14,2020-07-14,2020-07-13,BR,BRA,America,20286,733,1884967,72833,140
4327,Brazil,2020-07-15,2020-07-15,2020-07-14,BR,BRA,America,41857,1300,1926824,74133,141
4328,Brazil,2020-07-16,2020-07-16,2020-07-15,BR,BRA,America,39924,1233,1966748,75366,142
4329,Brazil,2020-07-17,2020-07-17,2020-07-16,BR,BRA,America,45403,1322,2012151,76688,143
4330,Brazil,2020-07-18,2020-07-18,2020-07-17,BR,BRA,America,34177,1163,2046328,77851,144
4331,Brazil,2020-07-19,2020-07-19,2020-07-18,BR,BRA,America,28532,921,2074860,78772,145
4332,Brazil,2020-07-20,2020-07-20,2020-07-19,BR,BRA,America,23529,716,2098389,79488,146
4333,Brazil,2020-07-21,2020-07-21,2020-07-20,BR,BRA,America,20257,632,2118646,80120,147
4334,Brazil,2020-07-22,2020-07-22,2020-07-21,BR,BRA,America,41008,1367,2159654,81487,148
4335,Brazil,2020-07-23,2020-07-23,2020-07-22,BR,BRA,America,67860,1284,2227514,82771,149
4336,Brazil,2020-07-24,2020-07-24,2020-07-23,BR,BRA,America,59961,1311,2287475,84082,150

In [39]:
covid_countries = covid_countries_reorder[['dateRep', 'datetime', 'cases_at', 'case_ordinalDay',
                                           'geoId', 'countries', 'countryCode', 'continent',
                                           'cases', 'deaths', 'cases_cumsum', 'deaths_cumsum']]

covid_countries.head()

,dateRep,datetime,cases_at,case_ordinalDay,geoId,countries,countryCode,continent,cases,deaths,cases_cumsum,deaths_cumsum
56,2020-02-25,2020-02-25,2020-02-24,1,AF,Afghanistan,AFG,Asia,1,0,1,0
57,2020-02-26,2020-02-26,2020-02-25,2,AF,Afghanistan,AFG,Asia,0,0,1,0
58,2020-02-27,2020-02-27,2020-02-26,3,AF,Afghanistan,AFG,Asia,0,0,1,0
59,2020-02-28,2020-02-28,2020-02-27,4,AF,Afghanistan,AFG,Asia,0,0,1,0
60,2020-02-29,2020-02-29,2020-02-28,5,AF,Afghanistan,AFG,Asia,0,0,1,0

In [40]:
covid_countries[(covid_countries.countries == 'Brazil') 
                & (covid_countries.cases_at >= '2020-02-25')]

,dateRep,datetime,cases_at,case_ordinalDay,geoId,countries,countryCode,continent,cases,deaths,cases_cumsum,deaths_cumsum
4187,2020-02-26,2020-02-26,2020-02-25,1,BR,Brazil,BRA,America,1,0,1,0
4188,2020-02-27,2020-02-27,2020-02-26,2,BR,Brazil,BRA,America,0,0,1,0
4189,2020-02-28,2020-02-28,2020-02-27,3,BR,Brazil,BRA,America,0,0,1,0
4190,2020-02-29,2020-02-29,2020-02-28,4,BR,Brazil,BRA,America,0,0,1,0
4191,2020-03-01,2020-03-01,2020-02-29,5,BR,Brazil,BRA,America,1,0,2,0
4192,2020-03-02,2020-03-02,2020-03-01,6,BR,Brazil,BRA,America,0,0,2,0
4193,2020-03-03,2020-03-03,2020-03-02,7,BR,Brazil,BRA,America,0,0,2,0
4194,2020-03-04,2020-03-04,2020-03-03,8,BR,Brazil,BRA,America,0,0,2,0
4195,2020-03-05,2020-03-05,2020-03-04,9,BR,Brazil,BRA,America,1,0,3,0
4196,2020-03-06,2020-03-06,2020-03-05,10,BR,Brazil,BRA,America,5,0,8,0
4197,2020-03-07,2020-03-07,2020-03-06,11,BR,Brazil,BRA,America,5,0,13,0
4198,2020-03-08,2020-03-08,2020-03-07,12,BR,Brazil,BRA,America,0,0,13,0
4199,2020-03-09,2020-03-09,2020-03-08,13,BR,Brazil,BRA,America,12,0,25,0
4200,2020-03-10,2020-03-10,2020-03-09,14,BR,Brazil,BRA,America,0,0,25,0
4201,2020-03-11,2020-03-11,2020-03-10,15,BR,Brazil,BRA,America,9,0,34,0
4202,2020-03-12,2020-03-12,2020-03-11,16,BR,Brazil,BRA,America,18,0,52,0
4203,2020-03-13,2020-03-13,2020-03-12,17,BR,Brazil,BRA,America,25,0,77,0
4204,2020-03-14,2020-03-14,2020-03-13,18,BR,Brazil,BRA,America,21,0,98,0
4205,2020-03-15,2020-03-15,2020-03-14,19,BR,Brazil,BRA,America,23,0,121,0
4206,2020-03-16,2020-03-16,2020-03-15,20,BR,Brazil,BRA,America,79,0,200,0
4207,2020-03-17,2020-03-17,2020-03-16,21,BR,Brazil,BRA,America,34,0,234,0
4208,2020-03-18,2020-03-18,2020-03-17,22,BR,Brazil,BRA,America,57,1,291,1
4209,2020-03-19,2020-03-19,2020-03-18,23,BR,Brazil,BRA,America,137,3,428,4
4210,2020-03-20,2020-03-20,2020-03-19,24,BR,Brazil,BRA,America,193,2,621,6
4211,2020-03-21,2020-03-21,2020-03-20,25,BR,Brazil,BRA,America,283,5,904,11
4212,2020-03-22,2020-03-22,2020-03-21,26,BR,Brazil,BRA,America,224,7,1128,18
4213,2020-03-23,2020-03-23,2020-03-22,27,BR,Brazil,BRA,America,418,7,1546,25
4214,2020-03-24,2020-03-24,2020-03-23,28,BR,Brazil,BRA,America,345,9,1891,34
4215,2020-03-25,2020-03-25,2020-03-24,29,BR,Brazil,BRA,America,310,12,2201,46
4216,2020-03-26,2020-03-26,2020-03-25,30,BR,Brazil,BRA,America,232,11,2433,57
...,...,...,...,...,...,...,...,...,...,...,...,...
4307,2020-06-25,2020-06-25,2020-06-24,121,BR,Brazil,BRA,America,42725,1185,1188631,53830
4308,2020-06-26,2020-06-26,2020-06-25,122,BR,Brazil,BRA,America,39483,1141,1228114,54971
4309,2020-06-27,2020-06-27,2020-06-26,123,BR,Brazil,BRA,America,46860,990,1274974,55961
4310,2020-06-28,2020-06-28,2020-06-27,124,BR,Brazil,BRA,America,38693,1109,1313667,57070
4311,2020-06-29,2020-06-29,2020-06-28,125,BR,Brazil,BRA,America,30476,552,1344143,57622
4312,2020-06-30,2020-06-30,2020-06-29,126,BR,Brazil,BRA,America,24052,692,1368195,58314
4313,2020-07-01,2020-07-01,2020-06-30,127,BR,Brazil,BRA,America,33846,1280,1402041,59594
4314,2020-07-02,2020-07-02,2020-07-01,128,BR,Brazil,BRA,America,46712,1038,1448753,60632
4315,2020-07-03,2020-07-03,2020-07-02,129,BR,Brazil,BRA,America,48105,1252,1496858,61884
4316,2020-07-04,2020-07-04,2020-07-03,130,BR,Brazil,BRA,America,42223,1290,1539081,63174
4317,2020-07-05,2020-07-05,2020-07-04,131,BR,Brazil,BRA,America,37923,1091,1577004,64265
4318,2020-07-06,2020-07-06,2020-07-05,132,BR,Brazil,BRA,America,26051,602,1603055,64867
4319,2020-07-07,2020-07-07,2020-07-06,133,BR,Brazil,BRA,America,20229,620,1623284,65487
4320,2020-07-08,2020-07-08,2020-07-07,134,BR,Brazil,BRA,America,45305,1254,1668589,66741
4321,2020-07-09,2020-07-09,2020-07-08,135,BR,Brazil,BRA,America,44571,1223,1713160,67964
4322,2020-07-10,2020-07-10,2020-07-09,136,BR,Brazil,BRA,America,42619,1220,1755779,69184
4323,2020-07-11,2020-07-11,2020-07-10,137,BR,Brazil,BRA,America,45048,1214,1800827,70398
4324,2020-07-12,2020-07-12,2020-07-11,138,BR,Brazil,BRA,America,39023,1071,1839850,71469
4325,2020-07-13,2020-07-13,2020-07-12,139,BR,Brazil,BRA,America,24831,631,1864681,72100
4326,2020-07-14,2020-07-14,2020-07-13,140,BR,Brazil,BRA,America,20286,733,1884967,72833
4327,2020-07-15,2020-07-15,2020-07-14,141,BR,Brazil,BRA,America,41857,1300,1926824,74133
4328,2020-07-16,2020-07-16,2020-07-15,142,BR,Brazil,BRA,America,39924,1233,1966748,75366
4329,2020-07-17,2020-07-17,2020-07-16,143,BR,Brazil,BRA,America,45403,1322,2012151,76688
4330,2020-07-18,2020-07-18,2020-07-17,144,BR,Brazil,BRA,America,34177,1163,2046328,77851
4331,2020-07-19,2020-07-19,2020-07-18,145,BR,Brazil,BRA,America,28532,921,2074860,78772
4332,2020-07-20,2020-07-20,2020-07-19,146,BR,Brazil,BRA,America,23529,716,2098389,79488
4333,2020-07-21,2020-07-21,2020-07-20,147,BR,Brazil,BRA,America,20257,632,2118646,80120
4334,2020-07-22,2020-07-22,2020-07-21,148,BR,Brazil,BRA,America,41008,1367,2159654,81487
4335,2020-07-23,2020-07-23,2020-07-22,149,BR,Brazil,BRA,America,67860,1284,2227514,82771
4336,2020-07-24,2020-07-24,2020-07-23,150,BR,Brazil,BRA,America,59961,1311,2287475,84082

## Just checking the dataframe

In [41]:
covid_countries.dtypes

dateRep            datetime64[ns]
datetime           datetime64[ns]
cases_at           datetime64[ns]
case_ordinalDay             int64
geoId                      object
countries                  object
countryCode                object
continent                  object
cases                       int64
deaths                      int64
cases_cumsum                int64
deaths_cumsum               int64
dtype: object

In [42]:
covid_countries.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28794 entries, 56 to 31804
Data columns (total 12 columns):
dateRep            28794 non-null datetime64[ns]
datetime           28794 non-null datetime64[ns]
cases_at           28794 non-null datetime64[ns]
case_ordinalDay    28794 non-null int64
geoId              28794 non-null object
countries          28794 non-null object
countryCode        28766 non-null object
continent          28794 non-null object
cases              28794 non-null int64
deaths             28794 non-null int64
cases_cumsum       28794 non-null int64
deaths_cumsum      28794 non-null int64
dtypes: datetime64[ns](3), int64(5), object(4)
memory usage: 4.1+ MB

## Comparing the old dataset with the new one

In [43]:
columns_name = ['dateRep', 'datetime', 'cases_at', 'case_ordinalDay', 'geoId',
                'countries', 'countryCode', 'continent', 'cases', 
                'deaths', 'cases_cumsum', 'deaths_cumsum']

covid_countries_old = pd.read_csv('~/covid-19/data/covid-19.csv', names=columns_name)

covid_countries_old['dateRep'] = pd.to_datetime(covid_countries_old['dateRep'])
covid_countries_old['datetime'] = pd.to_datetime(covid_countries_old['datetime'])
covid_countries_old['cases_at'] = pd.to_datetime(covid_countries_old['cases_at'])


covid_countries_old.head()

,dateRep,datetime,cases_at,case_ordinalDay,geoId,countries,countryCode,continent,cases,deaths,cases_cumsum,deaths_cumsum
0,2020-02-25,2020-02-25,2020-02-24,1,AF,Afghanistan,AFG,Asia,1,0,1,0
1,2020-02-26,2020-02-26,2020-02-25,2,AF,Afghanistan,AFG,Asia,0,0,1,0
2,2020-02-27,2020-02-27,2020-02-26,3,AF,Afghanistan,AFG,Asia,0,0,1,0
3,2020-02-28,2020-02-28,2020-02-27,4,AF,Afghanistan,AFG,Asia,0,0,1,0
4,2020-02-29,2020-02-29,2020-02-28,5,AF,Afghanistan,AFG,Asia,0,0,1,0

concat the two dataframes and remove all duplicates (keep=False). Leaving only the observation that were always differents from each other.

In [44]:
new_data = pd.concat([covid_countries_old, covid_countries]).drop_duplicates(keep=False)

new_data.head()

Empty DataFrame
Columns: [dateRep, datetime, cases_at, case_ordinalDay, geoId, countries, countryCode, continent, cases, deaths, cases_cumsum, deaths_cumsum]
Index: []

data_insert = new registration on a day

The new registrations is about registrations that don't have in our dataframe. So they are observations that has no duplication when I concat the new_data set (in terms of ['dateRep', 'case_ordinalDay', 'geoId', 'countries']) with the old one.

In [45]:
data_insert = new_data.drop_duplicates(subset=['dateRep', 'datetime', 'case_ordinalDay', 
                                               'countries', 'continent'], 
                                       keep=False)

data_insert.head()

Empty DataFrame
Columns: [dateRep, datetime, cases_at, case_ordinalDay, geoId, countries, countryCode, continent, cases, deaths, cases_cumsum, deaths_cumsum]
Index: []

creating data_update: removing data_insert from new_data

In [46]:
data_update = pd.concat([data_insert, new_data]).drop_duplicates(keep=False)

data_update.head()

Empty DataFrame
Columns: [dateRep, datetime, cases_at, case_ordinalDay, geoId, countries, countryCode, continent, cases, deaths, cases_cumsum, deaths_cumsum]
Index: []

proof: the len sum of data_update and data_insert is the same of the new_data len?

In [47]:
len(data_update) + len(data_insert) == len(new_data)

True

Now that we have a dataframe with different observations in data_update. But we have the different observation from old and another one from actual dataframe at the same day (remember, data_update is from new_data that is the concat of [covid_countries_old, covid_countries].drop_duplicates). Meaning in this we can have two observations at the same date, let's remove the last one and leaving the most recent occurrence, because this one is the new data that will be updated.

In [48]:
data_update = data_update.drop_duplicates(['dateRep', 'datetime', 'cases_at', 'case_ordinalDay',
                                           'geoId', 'countries', 'countryCode', 'continent'],
                                          keep='last')

data_update.head()

Empty DataFrame
Columns: [dateRep, datetime, cases_at, case_ordinalDay, geoId, countries, countryCode, continent, cases, deaths, cases_cumsum, deaths_cumsum]
Index: []

# Creating csv files with prepared dataset

In [49]:
covid_countries.to_csv(r'/home/gtrindadi/covid-19/data/covid-19.csv', index=False, header=False)

In [50]:
covid_today = covid_countries[covid_countries.datetime == today]
covid_today.to_csv(r'/home/gtrindadi/covid-19/data/covid-19-today.csv', index=False, header=False)

In [51]:
data_update.to_csv(r'/home/gtrindadi/covid-19/data/covid-19-update.csv', index=False, header=False)

In [52]:
data_insert = data_insert[data_insert.datetime != today]
data_insert.to_csv(r'/home/gtrindadi/covid-19/data/covid-19-insert.csv', index=False, header=False)